#!/usr/bin/env python3
"""
Fetch the latest release number for each OS and populate "releases" key in matrix.yml
with current and previous release numbers (building for last two major).

After polling lastversion, write out the load-bearing artifacts the rest of
the build system consumes:
  - buildstrap/matrix.json (and a copy in ../rpmbuilder/matrix.json) — the
    canonical machine-readable matrix the per-project generator
    (generate_circleci_config.py) reads.
  - buildstrap/matrix.sh — bash array of dist → distro/version, sourced by
    shell scripts (e.g. ~/scripts/upstream-check-and-build-all.sh).
  - ../rpmbuilder/distro_versions.json and defaults — feed the rpmbuilder
    image-build GitHub Action matrix.

The old generated_config{,_nginx,_self,_specs_only,_nginx_without_plesk}.yml
template writers retired 2026-06-12. Their consumers (~150 repos) all
migrated to per-project settings.yml + generate_circleci_config.py.
"""
import stat
import json

import lastversion
import yaml
import os

abspath = os.path.abspath(__file__)
os.chdir(os.path.dirname(abspath))
with open("matrix.yml", "r") as f:
    try:
        distros_config = yaml.safe_load(f)
    except yaml.YAMLError as exc:
        print(exc)
        exit(1)

distros = distros_config["distros"]
for distro, distro_config in distros.items():
    if "dir" not in distro_config:
        distro_config["dir"] = distro_config["dist"]
    if "versions_check" in distro_config and not distro_config["versions_check"]:
        continue
    distro_version = lastversion.latest(distro).release[0]
    print(f"Latest version for {distro} is {distro_version}")
    # array of OS releases, of course we build against the current version always:
    distros[distro]["versions"] = [distro_version]
    # build against that many past releases of OS
    os_versions = distro_config.get(
        "os_versions", distros_config["distro_defaults"]["os_versions"]
    )

    # now add past release of the OS:
    for i in range(1, os_versions):
        distros[distro]["versions"].append(distro_version - i)

    if distro_config.get("include_rolling_release", False):
        distros[distro]["versions"].append(distro_version + 1)

# write helper bash arrays for shell scripts
# declare -A dists=(
#   ["el6"]="redhat/6"
#   ["el7"]="redhat/7"
#   ["el8"]="redhat/8"
#   ["el9"]="redhat/9"
#   ["fc33"]="fedora/33"
#   ["fc34"]="fedora/34"
#   ["fc35"]="fedora/35"
#   ["fc36"]="fedora/36"
#   ["fc37"]="fedora/37"
#   ["amzn2"]="amzn/2"
#   ["sles15"]="sles/15"
# )
dists_array_s_list = [
    "#!/bin/bash",
    "# auto-generated by generate_config.py from matrix.yml",
    "# mapping of dists to directories:",
    "declare -A dists=(",
]
for distro_name, distro_config in distros.items():
    for v in distro_config["versions"]:
        line_fmt = '  ["{}"]="{}"'
        dists_array_s_list.append(
            line_fmt.format(
                f"{distro_config['dist']}{v}", f"{distro_config['dir']}/{v}"
            )
        )
dists_array_s_list.append(")")

dists_array_s_list.append("# mapping of directories to full descriptive names:")
# declare -A os_long=( ["redhat"]="CentOS/RHEL" ["amzn"]="Amazon Linux" ["fedora"]="Fedora Linux" )
dists_array_s_list.append("declare -A os_long=(")
for distro_name, distro_config in distros.items():
    line_fmt = '  ["{}"]="{}"'
    dists_array_s_list.append(
        line_fmt.format(f"{distro_config['dir']}", f"{distro_config['description']}")
    )
dists_array_s_list.append(")")
dists_array_s_list.append("")

with open("matrix.sh", "w") as f:
    f.write("\n".join(dists_array_s_list))

st = os.stat("matrix.sh")
os.chmod("matrix.sh", st.st_mode | stat.S_IEXEC)

# Generate matrix.json which is useful for Repo Explorer feature at GetPageSpeed
# Same as matrix.yml but in json format and with filled out versions
# Just json dump distros variables
with open("matrix.json", "w", encoding="utf-8") as f:
    json.dump(distros_config, f, indent=4)

# If rpmbuilder directory exists, cd into it, otherwise exit with error
if not os.path.exists("../rpmbuilder"):
    print("rpmbuilder directory not found")
    exit(1)

# cd into rpmbuilder directory
os.chdir("../rpmbuilder")

# Also write matrix.json for the rpmbuilder project
with open("matrix.json", "w", encoding="utf-8") as f:
    json.dump(distros_config, f, indent=4)

# Create special distro_versions.json for the rpmbuilder project
# Used in matrix: of its GitHub Actions workflow
distro_versions = []
for distro_name, distro_config in distros.items():
    for v in distro_config["versions"]:
        distro_versions.append({"os": distro_config["rpmbuilder_name"], "version": v})
with open("distro_versions.json", "w", encoding="utf-8") as f:
    json.dump({"include": distro_versions}, f, indent=4)

# Write defaults file as well:
default_lines = []
for distro_name, distro_config in distros.items():
    for v in distro_config["versions"]:
        default_lines.append(f"{distro_config['rpmbuilder_name']} {v}")
# write to defaults file at ../rpmbuilder/defaults
with open("defaults", "w", encoding="utf-8") as f:
    f.write("\n".join(default_lines))

print("Done")
