version: 2.1

executors:
  deploy:
    parameters:
      dist:
        type: string
    docker:
      - image: kroniak/ssh-client
    working_directory: /output
    environment:
      DISTRO: << parameters.dist >>
  rpmbuilder:
    parameters:
      dist:
        type: string
      rpmlint:
        type: integer
        default: 1
      plesk:
        type: integer
        default: 0
      mod:
        type: integer
        default: 0
    docker:
      - image: getpagespeed/rpmbuilder:<< parameters.dist >>
    working_directory: /sources
    environment:
      RPMLINT: << parameters.rpmlint >>
      PLESK: << parameters.plesk >>
      MOD: << parameters.mod >>
jobs:
  build:
    parameters:
      dist:
        description: "The dist tag of OS to build for"
        type: string
      plesk:
        description: "Plesk major release version number, e.g. 18"
        type: integer
        default: 0
      mod:
        type: integer
        default: 0
    resource_class: small
    executor:
      name: rpmbuilder
      dist: << parameters.dist >>
      plesk: << parameters.plesk >>
      mod: << parameters.mod >>
    steps:
      - checkout
      - run:
          name: "Set up RPM macro reflecting the NGINX branch"
          command: |
            echo "%nginx_branch ${CIRCLE_BRANCH}" >> rpmmacros
      - run:
          name: "Set up %plesk macro if passed by a job"
          command: |
            [ -z ${PLESK+x} ] || echo "%plesk ${PLESK}" >> rpmmacros
            # we generate both nginx-module-<foo> and sw-nginx-module-<foo> from a single spec file, so:
            [ -z ${PLESK+x} ] || (echo >> rpmlint.config && echo 'addFilter ("E: invalid-spec-name")' >> rpmlint.config)
            [ -z ${MOD+x} ] || echo "%_nginx_mod ${MOD}" >> rpmmacros
            [ -z ${MOD+x} ] || (echo >> rpmlint.config && echo 'addFilter ("E: invalid-spec-name")' >> rpmlint.config)
      - run:
          name: "Run script to cleanup spec files that don't need rebuilding"
          command: |
            [[ ! -f ./cleanup.sh ]] || BRANCH="${CIRCLE_BRANCH}" ./cleanup.sh
      - run:
          name: "Run the build itself: this will do rpmlint and check RPMs existence among other things."
          command: build
      - persist_to_workspace:
          root: /output
          paths:
            - "*.rpm"
  deploy:
    # one deploy at a time
    parallelism: 1
    parameters:
      dist:
        description: "The dist tag of OS to deploy for"
        type: string
    executor:
      name: deploy
      dist: << parameters.dist >>
    steps:
      - attach_workspace:
          at: /output
      - add_ssh_keys:
          fingerprints:
            - "8c:a4:dd:2c:47:4c:63:aa:90:0b:e0:d6:15:be:87:82"
      - run:
          name: "Ensure project specific upload directory to avoid deploy collisions"
          command: >
            ssh -o StrictHostKeyChecking=no
            $GPS_BUILD_USER@$GPS_BUILD_SERVER
            "mkdir -p ~/incoming/${CIRCLE_PROJECT_REPONAME}/${DISTRO}/${CIRCLE_BRANCH}"
      - run:
          name: "Deploy all RPMs to GetPageSpeed repo."
          command: >
            scp -o StrictHostKeyChecking=no -q -r *.rpm
            $GPS_BUILD_USER@$GPS_BUILD_SERVER:~/incoming/${CIRCLE_PROJECT_REPONAME}/${DISTRO}/${CIRCLE_BRANCH}/
      - run:
          name: "Trigger Deploy Hook."
          command: >
            ssh -o StrictHostKeyChecking=no -q
            $GPS_BUILD_USER@$GPS_BUILD_SERVER
            "nohup ~/scripts/incoming.sh ${CIRCLE_PROJECT_REPONAME}/${DISTRO}/${CIRCLE_BRANCH}/ > ~/incoming/$CIRCLE_PROJECT_REPONAME/$DISTRO/${CIRCLE_BRANCH}/process.log 2>&1&"
workflows:
  build-deploy-amzn2-mainline:
    jobs:
    - build:
        dist: amzn2
        filters:
          branches: {only: mainline}
        name: build-amzn2-mainline
    - deploy:
        context: org-global
        dist: amzn2
        filters:
          branches: {only: mainline}
        name: deploy-amzn2-mainline
        requires: [build-amzn2-mainline]
  build-deploy-amzn2-nginx-quic:
    jobs:
    - build:
        dist: amzn2
        filters:
          branches: {only: nginx-quic}
        name: build-amzn2-nginx-quic
    - deploy:
        context: org-global
        dist: amzn2
        filters:
          branches: {only: nginx-quic}
        name: deploy-amzn2-nginx-quic
        requires: [build-amzn2-nginx-quic]
  build-deploy-amzn2-stable:
    jobs:
    - build:
        dist: amzn2
        filters:
          branches: {only: master}
        name: build-amzn2-stable
    - deploy:
        context: org-global
        dist: amzn2
        filters:
          branches: {only: master}
        name: deploy-amzn2-stable
        requires: [build-amzn2-stable]
  build-deploy-el7-mainline:
    jobs:
    - build:
        dist: el7
        filters:
          branches: {only: mainline}
        name: build-el7-mainline
    - deploy:
        context: org-global
        dist: el7
        filters:
          branches: {only: mainline}
        name: deploy-el7-mainline
        requires: [build-el7-mainline]
  build-deploy-el7-nginx-mod:
    jobs:
    - build:
        dist: el7
        filters:
          branches: {only: nginx-mod}
        mod: 1
        name: build-el7-nginx-mod
    - deploy:
        context: org-global
        dist: el7
        filters:
          branches: {only: nginx-mod}
        name: deploy-el7-nginx-mod
        requires: [build-el7-nginx-mod]
  build-deploy-el7-nginx-quic:
    jobs:
    - build:
        dist: el7
        filters:
          branches: {only: nginx-quic}
        name: build-el7-nginx-quic
    - deploy:
        context: org-global
        dist: el7
        filters:
          branches: {only: nginx-quic}
        name: deploy-el7-nginx-quic
        requires: [build-el7-nginx-quic]
  build-deploy-el7-plesk:
    jobs:
    - build:
        dist: el7
        filters:
          branches: {only: plesk}
        name: build-el7-plesk
        plesk: 18
    - deploy:
        context: org-global
        dist: el7
        filters:
          branches: {only: plesk}
        name: deploy-el7-plesk
        requires: [build-el7-plesk]
  build-deploy-el7-stable:
    jobs:
    - build:
        dist: el7
        filters:
          branches: {only: master}
        name: build-el7-stable
    - deploy:
        context: org-global
        dist: el7
        filters:
          branches: {only: master}
        name: deploy-el7-stable
        requires: [build-el7-stable]
  build-deploy-el8-mainline:
    jobs:
    - build:
        dist: el8
        filters:
          branches: {only: mainline}
        name: build-el8-mainline
    - deploy:
        context: org-global
        dist: el8
        filters:
          branches: {only: mainline}
        name: deploy-el8-mainline
        requires: [build-el8-mainline]
  build-deploy-el8-nginx-quic:
    jobs:
    - build:
        dist: el8
        filters:
          branches: {only: nginx-quic}
        name: build-el8-nginx-quic
    - deploy:
        context: org-global
        dist: el8
        filters:
          branches: {only: nginx-quic}
        name: deploy-el8-nginx-quic
        requires: [build-el8-nginx-quic]
  build-deploy-el8-plesk:
    jobs:
    - build:
        dist: el8
        filters:
          branches: {only: plesk}
        name: build-el8-plesk
        plesk: 18
    - deploy:
        context: org-global
        dist: el8
        filters:
          branches: {only: plesk}
        name: deploy-el8-plesk
        requires: [build-el8-plesk]
  build-deploy-el8-stable:
    jobs:
    - build:
        dist: el8
        filters:
          branches: {only: master}
        name: build-el8-stable
    - deploy:
        context: org-global
        dist: el8
        filters:
          branches: {only: master}
        name: deploy-el8-stable
        requires: [build-el8-stable]
  build-deploy-el9-mainline:
    jobs:
    - build:
        dist: el9
        filters:
          branches: {only: mainline}
        name: build-el9-mainline
    - deploy:
        context: org-global
        dist: el9
        filters:
          branches: {only: mainline}
        name: deploy-el9-mainline
        requires: [build-el9-mainline]
  build-deploy-el9-nginx-quic:
    jobs:
    - build:
        dist: el9
        filters:
          branches: {only: nginx-quic}
        name: build-el9-nginx-quic
    - deploy:
        context: org-global
        dist: el9
        filters:
          branches: {only: nginx-quic}
        name: deploy-el9-nginx-quic
        requires: [build-el9-nginx-quic]
  build-deploy-el9-plesk:
    jobs:
    - build:
        dist: el9
        filters:
          branches: {only: plesk}
        name: build-el9-plesk
        plesk: 18
    - deploy:
        context: org-global
        dist: el9
        filters:
          branches: {only: plesk}
        name: deploy-el9-plesk
        requires: [build-el9-plesk]
  build-deploy-el9-stable:
    jobs:
    - build:
        dist: el9
        filters:
          branches: {only: master}
        name: build-el9-stable
    - deploy:
        context: org-global
        dist: el9
        filters:
          branches: {only: master}
        name: deploy-el9-stable
        requires: [build-el9-stable]
  build-deploy-fc36-mainline:
    jobs:
    - build:
        dist: fc36
        filters:
          branches: {only: mainline}
        name: build-fc36-mainline
    - deploy:
        context: org-global
        dist: fc36
        filters:
          branches: {only: mainline}
        name: deploy-fc36-mainline
        requires: [build-fc36-mainline]
  build-deploy-fc36-nginx-quic:
    jobs:
    - build:
        dist: fc36
        filters:
          branches: {only: nginx-quic}
        name: build-fc36-nginx-quic
    - deploy:
        context: org-global
        dist: fc36
        filters:
          branches: {only: nginx-quic}
        name: deploy-fc36-nginx-quic
        requires: [build-fc36-nginx-quic]
  build-deploy-fc36-stable:
    jobs:
    - build:
        dist: fc36
        filters:
          branches: {only: master}
        name: build-fc36-stable
    - deploy:
        context: org-global
        dist: fc36
        filters:
          branches: {only: master}
        name: deploy-fc36-stable
        requires: [build-fc36-stable]
  build-deploy-fc37-mainline:
    jobs:
    - build:
        dist: fc37
        filters:
          branches: {only: mainline}
        name: build-fc37-mainline
    - deploy:
        context: org-global
        dist: fc37
        filters:
          branches: {only: mainline}
        name: deploy-fc37-mainline
        requires: [build-fc37-mainline]
  build-deploy-fc37-nginx-quic:
    jobs:
    - build:
        dist: fc37
        filters:
          branches: {only: nginx-quic}
        name: build-fc37-nginx-quic
    - deploy:
        context: org-global
        dist: fc37
        filters:
          branches: {only: nginx-quic}
        name: deploy-fc37-nginx-quic
        requires: [build-fc37-nginx-quic]
  build-deploy-fc37-stable:
    jobs:
    - build:
        dist: fc37
        filters:
          branches: {only: master}
        name: build-fc37-stable
    - deploy:
        context: org-global
        dist: fc37
        filters:
          branches: {only: master}
        name: deploy-fc37-stable
        requires: [build-fc37-stable]
  build-deploy-sles15-mainline:
    jobs:
    - build:
        dist: sles15
        filters:
          branches: {only: mainline}
        name: build-sles15-mainline
    - deploy:
        context: org-global
        dist: sles15
        filters:
          branches: {only: mainline}
        name: deploy-sles15-mainline
        requires: [build-sles15-mainline]
  build-deploy-sles15-nginx-quic:
    jobs:
    - build:
        dist: sles15
        filters:
          branches: {only: nginx-quic}
        name: build-sles15-nginx-quic
    - deploy:
        context: org-global
        dist: sles15
        filters:
          branches: {only: nginx-quic}
        name: deploy-sles15-nginx-quic
        requires: [build-sles15-nginx-quic]
  build-deploy-sles15-stable:
    jobs:
    - build:
        dist: sles15
        filters:
          branches: {only: master}
        name: build-sles15-stable
    - deploy:
        context: org-global
        dist: sles15
        filters:
          branches: {only: master}
        name: deploy-sles15-stable
        requires: [build-sles15-stable]
