version: 2.1

executors:
  deploy:
    parameters:
      dist:
        type: string
    docker:
      - image: kroniak/ssh-client
    working_directory: /output
    environment:
      DISTRO: << parameters.dist >>
  rpmbuilder:
    parameters:
      dist:
        type: string
      rpmlint:
        type: integer
        default: 1
    docker:
      - image: getpagespeed/rpmbuilder:<< parameters.dist >>
    working_directory: /sources
    environment:
      RPMLINT: << parameters.rpmlint >>
jobs:
  build:
    parameters:
      dist:
        description: "The dist tag of OS to build for"
        type: string
    resource_class: small
    executor:
      name: rpmbuilder
      dist: << parameters.dist >>
    steps:
      - checkout
      - run:
          name: "Run the build itself: this will do rpmlint and check RPMs existence among other things."
          command: ./utils/version-from-tag.sh && build
      - persist_to_workspace:
          root: /output
          paths:
            - "*.rpm"
  deploy:
    parameters:
      dist:
        description: "The dist tag of OS to deploy for"
        type: string
    executor:
      name: deploy
      dist: << parameters.dist >>
    steps:
      - attach_workspace:
          at: /output
      - add_ssh_keys:
          fingerprints:
            - "8c:a4:dd:2c:47:4c:63:aa:90:0b:e0:d6:15:be:87:82"
      - run:
          name: "Ensure project specific upload directory to avoid deploy collisions"
          command: >
            ssh -o StrictHostKeyChecking=no
            $GPS_BUILD_USER@$GPS_BUILD_SERVER
            "mkdir -p ~/incoming/$CIRCLE_PROJECT_REPONAME/$DISTRO"
      - run:
          name: "Deploy all RPMs to GetPageSpeed repo."
          command: >
            scp -o StrictHostKeyChecking=no -q -r *.rpm
            $GPS_BUILD_USER@$GPS_BUILD_SERVER:~/incoming/$CIRCLE_PROJECT_REPONAME/$DISTRO/
      - run:
          name: "Trigger Deploy Hook."
          command: >
            ssh -o StrictHostKeyChecking=no -q
            $GPS_BUILD_USER@$GPS_BUILD_SERVER
            "nohup ~/scripts/incoming.sh $CIRCLE_PROJECT_REPONAME/$DISTRO/ > ~/incoming/$CIRCLE_PROJECT_REPONAME/$DISTRO/process.log 2>&1&"
